[IN-1659] Update openjdk from 8 to 11
bitrise-io/android pull request #311
Opened 2020-08-19 07:44 UTC by fehersanyi-bitrise

### Pull Request Checklist

Check/accept these:

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I've updated the version in the Dockerfile
- [ ] I've updated the CHANGELOG.md
- [ ] I've provided a link or explanation below which describes the changes in the tool itself
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added

`Copy or link the tool's changelog here`

2020-08-19 07:47 UTC, peterheja-bitrise approved these changes
lgtm

2020-08-19 08:07 UTC, lmesz-bitrise approved these changes
How will we validate this change?

2020-08-19 10:02 UTC, bitrise-tom approved these changes

2020-08-19 14:49 UTC, lmesz-bitrise requested changes

2020-08-19 14:49 UTC, lmesz-bitrise commented on Dockerfile
> +ENV SDKMANAGER_PATH /opt/android-sdk-linux/cmdline-tools/tools/bin/sdkmanager
Please add it to the PATH? It will be a problem for the customer too if they won't be able to use sdkmanager.

2020-08-19 14:50 UTC, fehersanyi-bitrise commented on Dockerfile
> +ENV SDKMANAGER_PATH /opt/android-sdk-linux/cmdline-tools/tools/bin/sdkmanager
it is on path, it is just a make sure it is there because on mac I had to deal with crap so I'm now super explicit kind of movement 🧐

2020-08-19 14:57 UTC, lmesz-bitrise commented on Dockerfile
> +ENV SDKMANAGER_PATH /opt/android-sdk-linux/cmdline-tools/tools/bin/sdkmanager
If it is on the path then this step is unnecessary.
I am afraid if it does not work with PATH the reason is that it is another sdkmanager with different settings which can be resulted to install to not proper places

2020-08-19 15:13 UTC, lmesz-bitrise requested changes

2020-08-19 15:13 UTC, lmesz-bitrise commented on Dockerfile
> +RUN DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-8-jdk openjdk-11-jdk libc6:i386 libstdc++6:i386 libgcc1:i386 libncurses5:i386 libz1:i386 net-tools
Don't we need to remove openjdk-8-jdk?

2020-08-19 15:17 UTC, koral-- commented on Dockerfile
> +ENV SDKMANAGER_PATH /opt/android-sdk-linux/cmdline-tools/tools/bin/sdkmanager
Yep, it is possible. At the time of introducing commandline-tools (https://github.com/bitrise-io/android/pull/300) it needs to be located in the very specific location relative to $ANDROID_HOME.
Even after updating commandline-tools using `sdkmanager` provided by themselves, the new version was installed in a different location resulting in 2 sdk managers.
Maybe @fehersanyi-bitrise encountered something similar.

2020-08-24 08:39 UTC, lmesz-bitrise requested changes

2020-08-24 08:39 UTC, lmesz-bitrise commented on Dockerfile
> +RUN yes | sdkmanager --licenses
Moved the whitespace from before --license to after? :D

2020-08-24 08:39 UTC, lmesz-bitrise commented on Dockerfile
> +RUN DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-8-jdk openjdk-11-jdk libc6:i386 libstdc++6:i386 libgcc1:i386 libncurses5:i386 libz1:i386 net-tools
Please remove it!

2020-08-24 14:52 UTC, lmesz-bitrise approved these changes
![](https://media.giphy.com/media/xT0GqH01ZyKwd3aT3G/giphy.gif)

2020-08-25 09:57 UTC, bitrisekristof approved these changes

2020-08-25 09:57 UTC, merged