[IN-1842] Install Java 11 but keep Java 8 as default
bitrise-io/android pull request #315
Opened 2020-09-09 13:08 UTC by fehersanyi-bitrise

### Pull Request Checklist

Check/accept these:

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I've updated the version in the Dockerfile
- [ ] I've updated the CHANGELOG.md
- [ ] I've provided a link or explanation below which describes the changes in the tool itself
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added

`Copy or link the tool's changelog here`

2020-09-09 13:09 UTC, lmesz-bitrise submitted a review, later dismissed

2020-09-09 13:13 UTC, bitrise-tom approved these changes

2020-09-10 07:28 UTC, lmesz-bitrise commented on Dockerfile
> +RUN sudo update-java-alternatives --jre-headless --set java-1.8.0-openjdk-amd64
Why do you need to set it twice?

2020-09-10 08:04 UTC, fehersanyi-bitrise commented on Dockerfile
> +RUN sudo update-java-alternatives --jre-headless --set java-1.8.0-openjdk-amd64
because the gradle install for some reason changes it to 11
this is before: 
```
------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------
Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60
Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_265 (Private Build 25.265-b01)
OS:           Linux 4.4.0-57-generic amd64
```
and after the install
```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 11.0.5, vendor: Ubuntu
Java home: /usr/lib/jvm/java-11-openjdk-amd64
```

2020-09-10 08:09 UTC, lmesz-bitrise commented on Dockerfile
> +RUN sudo update-java-alternatives --jre-headless --set java-1.8.0-openjdk-amd64
It is not clear to me what should I see here. It is not an apple-to-apple comparison of the same command's output. Can you paste a `java -version` output before and after Gradle install?

2020-09-24 12:05 UTC, peterheja-bitrise approved these changes
LGTM

2020-09-24 12:08 UTC, peterheja-bitrise requested changes
Add `export JAVA_HOME="$(jenv prefix)"` to `.bashrc`.

https://github.com/bitrise-io/osx-box-bootstrap/pull/313/commits/6ea21581ef67686e25353f7e8ae1e067134a5cd0

2020-09-30 11:32 UTC, peterheja-bitrise commented
`export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64`

2020-09-30 11:34 UTC, peterheja-bitrise submitted a review, later dismissed
We should advise users on how to change.
But otherwise, this looks 👌

2020-09-30 13:16 UTC, koral-- commented on CHANGELOG.md
> +## `v2020+09_30_1`
```suggestion
## `v2020_09_30_1`
```

2020-09-30 13:26 UTC, fehersanyi-bitrise commented on CHANGELOG.md
> +## `v2020+09_30_1`
oh thank you for spotting!

2020-09-30 13:48 UTC, lmesz-bitrise approved these changes

2020-09-30 14:03 UTC, peterheja-bitrise approved these changes
LGTM

2020-09-30 14:11 UTC, merged